package com.softserve.edu.hw06;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class HwTst {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void HwTst1() {
        driver.get("https://www.greencity.cx.ua/#/ubs");
        driver.manage().window().setSize(new Dimension(1382, 744));
        driver.findElement(By.cssSelector("app-header:nth-child(1) .header_navigation-menu-ubs")).click();
        driver.findElement(By.cssSelector("app-header:nth-child(1) .nav-left-list:nth-child(4) > .url-name")).click();
        js.executeScript("window.scrollTo(0,1688.0999755859375)");
        driver.findElement(By.cssSelector(".nav-left-list:nth-child(1) > .url-name")).click();
        js.executeScript("window.scrollTo(0,0)");
        driver.findElement(By.cssSelector(".gallery-view-li-active:nth-child(1) .list-image-content")).click();
        js.executeScript("window.scrollTo(0,483)");
        driver.findElement(By.cssSelector(".comment-textarea")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".comment-textarea"));
            js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'test'}", element);
        }
        driver.findElement(By.cssSelector(".primary-global-button")).click();
    }
}
